version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./data/mongodb:/data/db
        ports:
            - 27017:21017
        restart: unless-stopped
        